#!/usr/bin/env python
# -*- coding: utf-8 -*-
import xml.etree.cElementTree as ET
import pprint
import re
"""
-find out how many unique users have contributed to the map in this particular area

The function process_map should return a set of unique user IDs ("uid")
"""

def get_user(element):   #get & count unique users (uid)  uid=
    #if element.tag == "node" or element.tag == "way" or element.tag =="relation":
    if element.attrib.get("uid"):
        uid = element.attrib["uid"]
        return uid
    else:
        return None
        
def process_map(filename):   #processing get_user
    users = set()
    for _, element in ET.iterparse(filename):
        if get_user(element):
            users.add(get_user(element))
    return users

def test():

    users = process_map('example.osm')
    pprint.pprint(users)
    assert len(users) == 6

if __name__ == "__main__":
    test()
